name: Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ "lts/*", 24, 22, 20 ]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npx c8 npm test
      - name: codecov
        uses: codecov/codecov-action@v3
